version: '3'
services:
    web:
        build:
            context: ./app
            dockerfile: docker/Dockerfile
        command: python /django/manage.py runserver 0.0.0.0:8000
        user: "1000:0"
        volumes:
            - ./app:/django/
        ports:
            - "80:8000"
        depends_on:
            - redis
            - pgsql
        networks:
            sail:
                ipv4_address: 172.22.0.2
    pgsql:
        image: 'postgres:15'
        user: "1000:0"
        environment:
            POSTGRES_DB: '{POSTGRES_DB}'
            POSTGRES_USER: '{POSTGRES_USER}'
            POSTGRES_PASSWORD: '{POSTGRES_PASSWORD}'
        volumes:
            - ./database/pgsql:/var/lib/postgresql/data
        networks:
            sail:
                ipv4_address: 172.22.0.3
    redis:
        image: 'redis:7.0.8'
        user: "1000:0"
        ports:
            - '6379:6379'
        volumes:
            - ./database/redis:/data
        networks:
            sail:
                ipv4_address: 172.22.0.4
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
        ipam:
            config:
                -   subnet: 172.22.0.0/16
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
